kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  #podSubnet: "10.10.0.0/16"
  #serviceSubnet: "10.11.0.0/16"
nodes:
- role: control-plane
  # No need `kindest/node:v1.27.1`, 
  #extraMounts:
  #- hostPath: OPT_CNI_BIN_PATH
  #  containerPath: /opt/cni/bin
- role: worker
- role: worker
