apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ros1-deamonset
spec:
  selector:
    matchLabels:
      app: ros1
  template:
    metadata:
      labels:
        app: ros1
    spec:
      containers:
      - name: ros1-master
        tty: true
        image: tomoyafujita/ros-noetic:latest
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/$ROS_DISTRO/setup.bash && roscore"]
        imagePullPolicy: IfNotPresent
      - name: ros1-talker
        tty: true
        image: tomoyafujita/ros-noetic:latest
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/$ROS_DISTRO/setup.bash && until rostopic list; do sleep 1; done && rostopic pub -r 1 chatter std_msgs/String \"Hello, world\""]
        imagePullPolicy: IfNotPresent
      - name: ros1-listener
        tty: true
        image: tomoyafujita/ros-noetic:latest
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/$ROS_DISTRO/setup.bash && until rostopic list; do sleep 1; done && rostopic echo chatter"]
        imagePullPolicy: IfNotPresent
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
